In [1]:
import numpy as np 
import pandas as pd

In [3]:
july_weather = pd.read_csv('/Users/quynhanh/Documents/SEMESTER/SEM5/Big Data/nyc_yellow_taxi_eta/data/weather_data/New York City,USA 2024-07-01 to 2024-07-31.csv')
august_weather = pd.read_csv('/Users/quynhanh/Documents/SEMESTER/SEM5/Big Data/nyc_yellow_taxi_eta/data/weather_data/New York City,USA 2024-08-01 to 2024-08-31.csv')
september_weather = pd.read_csv('/Users/quynhanh/Documents/SEMESTER/SEM5/Big Data/nyc_yellow_taxi_eta/data/weather_data/New York City,USA 2024-09-01 to 2024-09-30.csv')

july_weather.head()

,name,datetime,temp,feelslike,dew,humidity,precip,precipprob,preciptype,snow,...,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,conditions,icon,stations
0,"New York City,USA",2024-07-01T00:00:00,22.5,22.5,15.1,62.83,0.0,0,NaN,0,...,1012.7,88.9,16.0,0,0.0,0,10,Partially cloudy,partly-cloudy-night,"72505394728,KEWR,KLGA,72502014734,F1417,KNYC,7..."
1,"New York City,USA",2024-07-01T01:00:00,21.4,21.4,12.7,57.78,0.0,0,NaN,0,...,1012.8,80.1,16.0,0,0.0,0,10,Partially cloudy,partly-cloudy-night,"72505394728,KEWR,KLGA,72502014734,F8726,KNYC,7..."
2,"New York City,USA",2024-07-01T02:00:00,20.6,20.6,10.9,53.70,0.0,0,NaN,0,...,1012.8,37.0,16.0,0,0.0,0,10,Partially cloudy,partly-cloudy-night,"72505394728,KEWR,KLGA,72502014734,F8726,KNYC,7..."
3,"New York City,USA",2024-07-01T03:00:00,19.0,19.0,11.2,60.55,0.0,0,NaN,0,...,1013.4,15.6,16.0,0,0.0,0,10,Clear,clear-night,"72505394728,KEWR,KLGA,72502014734,F8726,KNYC,7..."
4,"New York City,USA",2024-07-01T04:00:00,18.5,18.5,11.3,62.81,0.0,0,NaN,0,...,1014.1,6.1,16.0,0,0.0,0,10,Clear,clear-night,"72505394728,KEWR,KLGA,72502014734,F8726,KNYC,7..."

In [15]:
merged_weather = pd.concat([july_weather, august_weather, september_weather], ignore_index=True)
merged_weather.head()

,name,datetime,temp,feelslike,dew,humidity,precip,precipprob,preciptype,snow,...,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,conditions,icon,stations
0,"New York City,USA",2024-07-01T00:00:00,22.5,22.5,15.1,62.83,0.0,0,NaN,0,...,1012.7,88.9,16.0,0,0.0,0,10,Partially cloudy,partly-cloudy-night,"72505394728,KEWR,KLGA,72502014734,F1417,KNYC,7..."
1,"New York City,USA",2024-07-01T01:00:00,21.4,21.4,12.7,57.78,0.0,0,NaN,0,...,1012.8,80.1,16.0,0,0.0,0,10,Partially cloudy,partly-cloudy-night,"72505394728,KEWR,KLGA,72502014734,F8726,KNYC,7..."
2,"New York City,USA",2024-07-01T02:00:00,20.6,20.6,10.9,53.70,0.0,0,NaN,0,...,1012.8,37.0,16.0,0,0.0,0,10,Partially cloudy,partly-cloudy-night,"72505394728,KEWR,KLGA,72502014734,F8726,KNYC,7..."
3,"New York City,USA",2024-07-01T03:00:00,19.0,19.0,11.2,60.55,0.0,0,NaN,0,...,1013.4,15.6,16.0,0,0.0,0,10,Clear,clear-night,"72505394728,KEWR,KLGA,72502014734,F8726,KNYC,7..."
4,"New York City,USA",2024-07-01T04:00:00,18.5,18.5,11.3,62.81,0.0,0,NaN,0,...,1014.1,6.1,16.0,0,0.0,0,10,Clear,clear-night,"72505394728,KEWR,KLGA,72502014734,F8726,KNYC,7..."

In [16]:
merged_weather['datetime'] = pd.to_datetime(merged_weather['datetime'])

merged_weather['date'] = merged_weather['datetime'].dt.date
merged_weather['time'] = merged_weather['datetime'].dt.time

merged_weather['day'] = merged_weather['datetime'].dt.day
merged_weather['month'] = merged_weather['datetime'].dt.month
merged_weather['hour'] = merged_weather['datetime'].dt.hour

merged_weather.head()

,name,datetime,temp,feelslike,dew,humidity,precip,precipprob,preciptype,snow,...,uvindex,severerisk,conditions,icon,stations,date,time,day,month,hour
0,"New York City,USA",2024-07-01 00:00:00,22.5,22.5,15.1,62.83,0.0,0,NaN,0,...,0,10,Partially cloudy,partly-cloudy-night,"72505394728,KEWR,KLGA,72502014734,F1417,KNYC,7...",2024-07-01,00:00:00,1,7,0
1,"New York City,USA",2024-07-01 01:00:00,21.4,21.4,12.7,57.78,0.0,0,NaN,0,...,0,10,Partially cloudy,partly-cloudy-night,"72505394728,KEWR,KLGA,72502014734,F8726,KNYC,7...",2024-07-01,01:00:00,1,7,1
2,"New York City,USA",2024-07-01 02:00:00,20.6,20.6,10.9,53.70,0.0,0,NaN,0,...,0,10,Partially cloudy,partly-cloudy-night,"72505394728,KEWR,KLGA,72502014734,F8726,KNYC,7...",2024-07-01,02:00:00,1,7,2
3,"New York City,USA",2024-07-01 03:00:00,19.0,19.0,11.2,60.55,0.0,0,NaN,0,...,0,10,Clear,clear-night,"72505394728,KEWR,KLGA,72502014734,F8726,KNYC,7...",2024-07-01,03:00:00,1,7,3
4,"New York City,USA",2024-07-01 04:00:00,18.5,18.5,11.3,62.81,0.0,0,NaN,0,...,0,10,Clear,clear-night,"72505394728,KEWR,KLGA,72502014734,F8726,KNYC,7...",2024-07-01,04:00:00,1,7,4

In [17]:
merged_weather.drop(['feelslike', 'dew', 'precipprob', 'preciptype', 'snow', 'conditions', 'icon', 'stations', 'uvindex', 'sealevelpressure', 'solarenergy', 'solarradiation', 'snowdepth'], axis=1, inplace=True)
merged_weather.head()

,name,datetime,temp,humidity,precip,windgust,windspeed,winddir,cloudcover,visibility,severerisk,date,time,day,month,hour
0,"New York City,USA",2024-07-01 00:00:00,22.5,62.83,0.0,38.0,28.8,324,88.9,16.0,10,2024-07-01,00:00:00,1,7,0
1,"New York City,USA",2024-07-01 01:00:00,21.4,57.78,0.0,40.7,11.9,324,80.1,16.0,10,2024-07-01,01:00:00,1,7,1
2,"New York City,USA",2024-07-01 02:00:00,20.6,53.70,0.0,38.9,12.7,328,37.0,16.0,10,2024-07-01,02:00:00,1,7,2
3,"New York City,USA",2024-07-01 03:00:00,19.0,60.55,0.0,48.4,14.5,328,15.6,16.0,10,2024-07-01,03:00:00,1,7,3
4,"New York City,USA",2024-07-01 04:00:00,18.5,62.81,0.0,40.7,10.4,320,6.1,16.0,10,2024-07-01,04:00:00,1,7,4

In [18]:
merged_weather.to_csv('merged_weather.csv', index=False)